import { PatternMeta } from "@/components/pattern/Patternmeta";
import { Tagline } from "@/components/pattern/Tagline";
import { Callout } from "@/components/pattern/Callout";
import { StructureDiagram } from "@/components/pattern/Struturediagram";
import { DoAndDont } from "@/components/pattern/Doanddont";
import { RealWorldExamples } from "@/components/pattern/Realworldexamples";
import { KeyTakeaway } from "@/components/pattern/Keytakeaway";
import { PatternNav } from "@/components/patternnav/PatternNav";
import { GitBranch } from "lucide-react";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Strategy Pattern",
  description: "Generated by create next app",
};

const data = {
  title: "Strategy Pattern",
  pattern: "Behavioral" as const,
  difficulty: "Beginner" as const,
};

export default function StrategyPatternPage() {
  return (
    <article className="mx-auto max-w-3xl px-6 py-10">
      <PatternMeta pattern={data.pattern} difficulty={data.difficulty} />

      <div className="flex items-center justify-between mt-2 mb-4">
        <h1 className="text-3xl font-semibold text-gray-900">
          Strategy Pattern
        </h1>
        <a
          href="https://github.com/manikandaprabhu0512/system-design-LLD/tree/main/Patterns/Strategy_Pattern"
          target="_blank"
          rel="noopener noreferrer"
          className="flex items-center gap-1.5 text-xs text-gray-400 hover:text-gray-700 border border-gray-200 hover:border-gray-300 rounded-md px-2.5 py-1.5 transition-colors"
        >
          <GitBranch size={13} />
          View code
        </a>
      </div>

      <Tagline>
        "Same goal, swappable approach - pick the algorithm at runtime, not at
        compile time."
      </Tagline>

      <hr className="my-8 border-gray-100" />

      {/* The Problem */}
      <h2 className="text-xl font-semibold text-gray-800 mb-3">The problem</h2>
      <p className="text-gray-600 leading-relaxed mb-4">
        Imagine you're building a payment system. First you support credit card.
        Then UPI. Then PayPal. Each time you add one, you're stuffing more{" "}
        <code className="text-sm bg-gray-100 px-1.5 py-0.5 rounded text-gray-700">
          if-else
        </code>{" "}
        into the same{" "}
        <code className="text-sm bg-gray-100 px-1.5 py-0.5 rounded text-gray-700">
          PaymentProcessor
        </code>{" "}
        class.
      </p>

      <pre className="bg-gray-950 text-gray-100 rounded-lg px-5 py-4 text-sm leading-relaxed overflow-x-auto mb-4">
        <code>{`// This is what you want to avoid
void processPayment(String type, int amount) {
    if (type.equals("creditcard")) {
        // credit card logic
    } else if (type.equals("upi")) {
        // upi logic
    } else if (type.equals("paypal")) {
        // paypal logic - now you're touching credit card code to add this
    }
}`}</code>
      </pre>

      <p className="text-gray-600 leading-relaxed mb-4">
        It works - but changing credit card logic risks breaking PayPal, and
        adding GPay means touching a class that should have nothing to do with
        GPay internals.
      </p>

      <Callout type="warning">
        The deeper issue: the class is responsible for <strong>what</strong> to
        do and <strong>how</strong> to do it. Strategy separates these two
        concerns.
      </Callout>

      <hr className="my-8 border-gray-100" />

      {/* The Solution */}
      <h2 className="text-xl font-semibold text-gray-800 mb-3">The solution</h2>
      <p className="text-gray-600 leading-relaxed mb-6">
        Extract each algorithm into its own class behind a common interface. The
        main class holds a reference to that interface - it doesn't know or care
        which concrete strategy is plugged in. Swap the strategy object, and the
        behavior changes at runtime.
      </p>

      <StructureDiagram pattern="strategy" />

      <hr className="my-8 border-gray-100" />

      {/* Code */}
      <h2 className="text-xl font-semibold text-gray-800 mb-3">Code</h2>

      <pre className="bg-gray-950 text-gray-100 rounded-lg px-5 py-4 text-sm leading-relaxed overflow-x-auto mb-4">
        <code>{`// 1. Strategy interface
interface PaymentStrategy {
    void pay(int amount);
}

// 2. Concrete strategies - each in its own class, isolated from others
class CreditCardStrategy implements PaymentStrategy {
    public void pay(int amount) {
        System.out.println("Paid ₹" + amount + " via Credit Card");
    }
}

class UpiStrategy implements PaymentStrategy {
    public void pay(int amount) {
        System.out.println("Paid ₹" + amount + " via UPI");
    }
}

class PayPalStrategy implements PaymentStrategy {
    public void pay(int amount) {
        System.out.println("Paid ₹" + amount + " via PayPal");
    }
}

// 3. Context - doesn't know which strategy it's using
class PaymentProcessor {
    private PaymentStrategy strategy;

    void setStrategy(PaymentStrategy strategy) {
        this.strategy = strategy;
    }

    void processPayment(int amount) {
        strategy.pay(amount); // delegates - doesn't care who handles it
    }
}

// 4. Usage - swap at runtime, no if-else needed
PaymentProcessor processor = new PaymentProcessor();

processor.setStrategy(new UpiStrategy());
processor.processPayment(500);  // Paid ₹500 via UPI

processor.setStrategy(new CreditCardStrategy());
processor.processPayment(200);  // Paid ₹200 via Credit Card`}</code>
      </pre>

      <Callout type="info">
        Adding GPay now means creating a new{" "}
        <code className="text-sm bg-blue-100 px-1.5 py-0.5 rounded">
          GPayStrategy
        </code>{" "}
        class - you never touch{" "}
        <code className="text-sm bg-blue-100 px-1.5 py-0.5 rounded">
          PaymentProcessor
        </code>{" "}
        or any existing strategy.
      </Callout>

      <hr className="my-8 border-gray-100" />

      {/* Deep Dive Example */}
      <h2 className="text-xl font-semibold text-gray-800 mb-3">
        Deep dive example - Robot
      </h2>
      <p className="text-gray-600 leading-relaxed mb-4">
        Let's go deeper with a classic example. You're designing a{" "}
        <code className="text-sm bg-gray-100 px-1.5 py-0.5 rounded text-gray-700">
          Robot
        </code>{" "}
        that can talk, walk, and fly. Different robots behave differently - a{" "}
        <code className="text-sm bg-gray-100 px-1.5 py-0.5 rounded text-gray-700">
          Humanoid
        </code>{" "}
        talks and walks but doesn't fly, while a{" "}
        <code className="text-sm bg-gray-100 px-1.5 py-0.5 rounded text-gray-700">
          Worker
        </code>{" "}
        walks but neither talks nor flies.
      </p>

      <p className="text-gray-600 leading-relaxed mb-6">
        Instead of hardcoding behaviors inside each robot subclass, Strategy
        pulls them out into separate abstractions. The robot{" "}
        <strong>has-a</strong> behavior rather than <strong>is-a</strong>{" "}
        behavior - that's the key insight.
      </p>

      {/* has-a vs is-a callout */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-6">
        <div className="bg-violet-50 border border-violet-200 rounded-lg p-4">
          <p className="text-xs font-semibold text-violet-600 uppercase tracking-wide mb-2">
            has-a (composition)
          </p>
          <p className="text-sm text-violet-900 leading-relaxed">
            <code className="bg-violet-100 px-1 rounded">Robot</code> holds a
            reference to{" "}
            <code className="bg-violet-100 px-1 rounded">TalkStrategy</code>,{" "}
            <code className="bg-violet-100 px-1 rounded">WalkStrategy</code>,{" "}
            <code className="bg-violet-100 px-1 rounded">FlyStrategy</code>.
            Swap any one at runtime without touching the Robot class.
          </p>
        </div>
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
          <p className="text-xs font-semibold text-blue-600 uppercase tracking-wide mb-2">
            is-a (inheritance)
          </p>
          <p className="text-sm text-blue-900 leading-relaxed">
            <code className="bg-blue-100 px-1 rounded">Humanoid</code> and{" "}
            <code className="bg-blue-100 px-1 rounded">Worker</code> extend{" "}
            <code className="bg-blue-100 px-1 rounded">Robot</code>. They
            inherit structure but plug in different strategy implementations.
          </p>
        </div>
      </div>

      {/* Abstracts explanation */}
      <p className="text-gray-600 leading-relaxed mb-4">
        Each behavior is defined as an abstract class with concrete
        implementations:
      </p>

      <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 mb-6">
        {[
          {
            abstract: "talk",
            method: "talk()",
            impls: ["talk - talks normally", "noTalk - stays silent"],
          },
          {
            abstract: "walk",
            method: "walk()",
            impls: ["walk - walks normally", "noWalk - stays still"],
          },
          {
            abstract: "fly",
            method: "fly()",
            impls: ["fly - flies normally", "noFly - cannot fly"],
          },
        ].map((b) => (
          <div
            key={b.abstract}
            className="bg-gray-50 border border-gray-200 rounded-lg p-3"
          >
            <p className="text-xs text-gray-400 mb-1">{"<<abstract>>"}</p>
            <p className="text-sm font-semibold text-gray-800 mb-1">
              {b.abstract}
            </p>
            <code className="text-xs bg-gray-100 px-1.5 py-0.5 rounded text-gray-600 block mb-2">
              {b.method}
            </code>
            <ul className="space-y-1">
              {b.impls.map((i) => (
                <li key={i} className="text-xs text-gray-500">
                  → {i}
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>

      {/* Robot code */}
      <pre className="bg-gray-950 text-gray-100 rounded-lg px-5 py-4 text-sm leading-relaxed overflow-x-auto mb-4">
        <code>{`// Abstract behavior strategies
abstract class TalkStrategy { abstract void talk(); }
abstract class WalkStrategy { abstract void walk(); }
abstract class FlyStrategy  { abstract void fly();  }

// Concrete implementations
class Talk   extends TalkStrategy { void talk() { System.out.println("Talking...");    } }
class NoTalk extends TalkStrategy { void talk() { System.out.println("Cannot talk.");  } }

class Walk   extends WalkStrategy { void walk() { System.out.println("Walking...");    } }
class NoWalk extends WalkStrategy { void walk() { System.out.println("Cannot walk.");  } }

class Fly    extends FlyStrategy  { void fly()  { System.out.println("Flying...");     } }
class NoFly  extends FlyStrategy  { void fly()  { System.out.println("Cannot fly.");   } }

// Context - Robot has-a strategy for each behavior
abstract class Robot {
    WalkStrategy w;
    FlyStrategy  f;
    TalkStrategy talk;

    abstract void projection();

    void performTalk() { talk.talk(); }
    void performWalk() { walk.walk(); }
    void performFly()  { fly.fly(); }
}

// Concrete robots - plug in the right strategies
class Humanoid extends Robot {
    Humanoid() {
        talk = new Talk();    // talks
        walk = new Walk();    // walks
        fly = new NoFly();   // doesn't fly
    }
    void projection() { System.out.println("Humanoid robot"); }
}

class Worker extends Robot {
    Worker() {
        talk = new NoTalk();  // doesn't talk
        walk = new Walk();    // walks
        fly = new NoFly();   // doesn't fly
    }
    void projection() { System.out.println("Worker robot"); }
}`}</code>
      </pre>

      <Callout type="tip">
        Want to give a Worker the ability to talk later? Just call{" "}
        <code className="text-sm bg-emerald-100 px-1.5 py-0.5 rounded">
          worker.talk = new Talk()
        </code>{" "}
        at runtime - no subclass changes, no new class needed. That's the power
        of <strong>composition over inheritance</strong>.
      </Callout>

      <hr className="my-8 border-gray-100" />

      {/* When to use / avoid */}
      <h2 className="text-xl font-semibold text-gray-800 mb-3">
        When to use / avoid
      </h2>
      <DoAndDont
        use={[
          "You have multiple ways to do the same thing and need to switch between them",
          "You want to add new behaviors without modifying existing code (Open/Closed Principle)",
          "You have a class with a large conditional that selects between variants of the same algorithm",
        ]}
        avoid={[
          "You only ever have one algorithm that never changes - the extra interface is overhead",
          "The strategies don't share any common behavior - a simpler conditional might be cleaner",
        ]}
      />

      <hr className="my-8 border-gray-100" />

      {/* Real-world examples */}
      <h2 className="text-xl font-semibold text-gray-800 mb-3">
        Real-world examples
      </h2>
      <RealWorldExamples
        examples={[
          {
            name: "Java Collections",
            detail:
              "Comparator passed to sort() - you define the strategy, Collections uses it",
          },
          {
            name: "Spring Security",
            detail:
              "Swappable authentication providers (JWT, OAuth, Basic Auth)",
          },
          {
            name: "Payment SDKs",
            detail:
              "Razorpay, Stripe, PayPal - same interface, different provider",
          },
          {
            name: "Game AI",
            detail:
              "Easy / medium / hard difficulty as swappable behavior strategies",
          },
          {
            name: "Compression libs",
            detail: "ZIP, GZIP, BZIP2 behind a common Compressor interface",
          },
        ]}
      />

      <hr className="my-8 border-gray-100" />

      {/* Key takeaway */}
      <h2 className="text-xl font-semibold text-gray-800 mb-3">Key takeaway</h2>
      <KeyTakeaway>
        Strategy lets you follow the Open/Closed Principle cleanly - open for
        extension (add a new strategy class), closed for modification (don't
        touch the context). If you find yourself writing{" "}
        <code className="text-sm bg-emerald-100 px-1.5 py-0.5 rounded">
          if (type == "X") ... else if (type == "Y")
        </code>{" "}
        for behavior, Strategy is likely the fix.
      </KeyTakeaway>

      <PatternNav
        prev={{
          title: "Solid Principles",
          pattern: "Concepts",
          href: "/lld/solid-principles",
        }}
        next={{
          title: "Factory Pattern",
          pattern: "Creational",
          href: "/lld/patterns/factory",
        }}
      />
    </article>
  );
}
