const strategy: React.ReactNode = (
  <svg
    viewBox="0 0 630 190"
    className="w-full"
    xmlns="http://www.w3.org/2000/svg"
  >
    <defs>
      <marker
        id="arr-s"
        viewBox="0 0 10 10"
        refX="8"
        refY="5"
        markerWidth="6"
        markerHeight="6"
        orient="auto"
      >
        <path
          d="M2 1L8 5L2 9"
          fill="none"
          stroke="#9ca3af"
          strokeWidth="1.5"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </marker>
      <marker
        id="triangle-sf"
        viewBox="0 0 10 10"
        refX="9"
        refY="5"
        markerWidth="8"
        markerHeight="8"
        orient="auto"
      >
        <path
          d="M0 0L10 5L0 10Z"
          fill="white"
          stroke="#9ca3af"
          strokeWidth="1"
        />
      </marker>
    </defs>
    <rect
      x="40"
      y="10"
      width="160"
      height="64"
      rx="8"
      fill="#f0fdf4"
      stroke="#6ee7b7"
      strokeWidth="1"
    />
    <text
      x="120"
      y="38"
      textAnchor="middle"
      fill="#065f46"
      fontSize="13"
      fontWeight="500"
    >
      Context
    </text>
    <text x="120" y="58" textAnchor="middle" fill="#6b7280" fontSize="11">
      - strategy: Strategy
    </text>
    <line
      x1="200"
      y1="42"
      x2="256"
      y2="42"
      stroke="#9ca3af"
      strokeWidth="1"
      markerEnd="url(#arr-s)"
    />
    <text x="228" y="34" textAnchor="middle" fill="#9ca3af" fontSize="10">
      uses
    </text>
    <rect
      x="258"
      y="10"
      width="160"
      height="64"
      rx="8"
      fill="#ede9fe"
      stroke="#c4b5fd"
      strokeWidth="1"
    />
    <text x="338" y="34" textAnchor="middle" fill="#5b21b6" fontSize="11">
      «interface»
    </text>
    <text
      x="338"
      y="52"
      textAnchor="middle"
      fill="#5b21b6"
      fontSize="13"
      fontWeight="500"
    >
      Strategy
    </text>
    <text x="338" y="68" textAnchor="middle" fill="#7c3aed" fontSize="11">
      + execute()
    </text>
    <line
      x1="338"
      y1="106"
      x2="338"
      y2="74"
      stroke="#9ca3af"
      strokeWidth="1"
      strokeDasharray="4 3"
      markerEnd="url(#triangle-sf)"
    />
    <line
      x1="160"
      y1="106"
      x2="516"
      y2="106"
      stroke="#9ca3af"
      strokeWidth="1"
    />
    <line
      x1="160"
      y1="106"
      x2="160"
      y2="126"
      stroke="#9ca3af"
      strokeWidth="1"
      strokeDasharray="4 3"
    />
    <line
      x1="338"
      y1="106"
      x2="338"
      y2="126"
      stroke="#9ca3af"
      strokeWidth="1"
      strokeDasharray="4 3"
    />
    <line
      x1="516"
      y1="106"
      x2="516"
      y2="126"
      stroke="#9ca3af"
      strokeWidth="1"
      strokeDasharray="4 3"
    />
    <rect
      x="80"
      y="126"
      width="160"
      height="48"
      rx="8"
      fill="#f9fafb"
      stroke="#d1d5db"
      strokeWidth="1"
    />
    <text
      x="160"
      y="154"
      textAnchor="middle"
      fill="#374151"
      fontSize="12"
      fontWeight="500"
    >
      CreditCardStrategy
    </text>
    <rect
      x="258"
      y="126"
      width="160"
      height="48"
      rx="8"
      fill="#f9fafb"
      stroke="#d1d5db"
      strokeWidth="1"
    />
    <text
      x="338"
      y="154"
      textAnchor="middle"
      fill="#374151"
      fontSize="12"
      fontWeight="500"
    >
      UpiStrategy
    </text>
    <rect
      x="436"
      y="126"
      width="160"
      height="48"
      rx="8"
      fill="#f9fafb"
      stroke="#d1d5db"
      strokeWidth="1"
    />
    <text
      x="516"
      y="154"
      textAnchor="middle"
      fill="#374151"
      fontSize="12"
      fontWeight="500"
    >
      PayPalStrategy
    </text>
  </svg>
);

export default strategy;
